## **机器学习算法的过程**
以红/白细胞的分类为例，讨论机器学习算法的完整流程。

**原料**：红，白细胞的图片(带标注)

**步骤**：

1.**特征提取**：通过训练样本获得的，对机器学习有帮助的多维度数据。

观察数据，建立初步认识后，提取特征信息。如观察白细胞和红细胞之后，发现白细胞通常更大，红细胞比白细胞更圆，白细胞内部的纹理比红细胞粗糙，因此初步确定特征：细胞的面积，圆形度，表面的粗糙程度。

2.**特征取舍**：通过画图，观察两类细胞是否能被选取的特征分割开，以此来确定特征的取舍。比如这个案例，在验证之后，发现面积和周长是比较好的特征。

3.**构建机器学习算法**：选用适用的机器学习算法。

**特征的选取和机器学习的算法的选择都非常重要**。但特征选取针对不同的任务，方法多种多样，课程上一般使用已经提取好的特征，讨论不同的机器学习算法的使用。

---------------------------------------------------------------------------

## **机器学习算法按照学习方式分类**

**监督学习（Supervised Learning）**

分类算法（如决策树、支持向量机、朴素贝叶斯、K最近邻等）

回归算法（如线性回归、岭回归、套索回归等）

**无监督学习（Unsupervised Learning）**

聚类算法（如K-均值、层次聚类、DBSCAN等）

关联规则学习（如Apriori算法、Eclat算法等）

降维算法（如主成分分析PCA、线性判别分析LDA等）

**半监督学习（Semi-supervised Learning）**

结合了监督学习和无监督学习的特点，使用部分标记的数据进行学习。

**强化学习（Reinforcement Learning）**

通过与环境交互来学习达到目标的最优策略。

## **数据预处理**

常见的数据预处理操作有：数据清洗、归一化、数据降维、数据集划分等。



### **数据清洗**

**数据清洗的主要内容包括(主要实现在Hands_On_Python的11-pandas中)：**

**缺失值处理**识别数据集中的缺失值，并根据情况选择填充缺失值（如使用均值、中位数、众数或插值法）或删除含有缺失值的记录。

**噪声处理**识别并处理数据集中的噪声，噪声可以是随机错误或异常值。处理方法包括平滑技术、分箱、聚类等。

**重复值处理**识别并删除数据集中的重复记录。

**数据一致性处理**确保数据集中的信息一致，例如统一日期格式、缩写、计量单位等。

**数据整合**合并来自不同来源的数据，解决数据之间的矛盾和差异。

**异常值检测和处理**识别数据集中的异常值，并决定是将其删除、修正还是保留。

**数据类型转换**确保每个字段的数据类型正确，例如将字符串转换为日期格式，或将文本转换为数值编码。

### **数据归一化**

#### 最大-最小归一化（Min-Max Scaling）
将数据线性的映射到[0, 1]

* 具体公式：$x^* = {x - \min(x) \over \max(x) - \min(x)}$，其中$x$是原始数据，$x^*$是归一化后的数据。

* **特点：**

    * 线性变换，保留数据的相对比例（最大值为1，最小值为0）

    * 对异常值非常敏感，特别是当异常值为最值时。

* **使用场景：**

    * 数据无明显偏差、且数值相对紧凑时

    * 使用模型需要基于距离计算时，如：KNN、K-Means、SVM等

In [7]:
import numpy as np

In [8]:
from sklearn.preprocessing import MinMaxScaler

# 最大-最小归一化
data = np.array([[2, 8], [4, 10], [6, 12], [8, 14]])

print("Min-Max归一化前的数据:\n", data)

# 创建MinMaxScaler，将数据缩放到[0, 1]范围内
scaler = MinMaxScaler()
data_normalized = scaler.fit_transform(data)

print("Min-Max归一化后的数据:\n", data_normalized)

Min-Max归一化前的数据:
 [[ 2  8]
 [ 4 10]
 [ 6 12]
 [ 8 14]]
Min-Max归一化后的数据:
 [[0.         0.        ]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]
 [1.         1.        ]]


#### 标准化(Z-score Normalization)

将数据映射到均值为0，方差为1的标准**正态分布（高斯分布）**

* 具体公式：$x^* = {x - \mu \over \sigma}$，其中$\mu$是数据的均值，$\sigma$是数据的方差  
* 特点：
  * 归一化后的数据取值范围为 $[-\infin, +\infin]$（正负皆有），但总体呈现标准正态分布
  * 对异常值不敏感
* **使用场景**：
  * 当数据分布存在**明显偏移**时（指各个特征的均值和方差相差很大）
  * 适用于基于**线性**假设的模型，如**线性回归、逻辑回归**等
  * 当不知道用哪种归一化方法时，通常标准化会更稳定

In [9]:
from sklearn.preprocessing import StandardScaler

data = np.array([[2, 8], [4, 10], [6, 12], [8, 14]])

print("标准化前的数据:\n", data)

# 创建StandardScaler
scaler = StandardScaler()
data_standardized = scaler.fit_transform(data)

print("标准化后的数据:\n", data_standardized)

标准化前的数据:
 [[ 2  8]
 [ 4 10]
 [ 6 12]
 [ 8 14]]
标准化后的数据:
 [[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]


### **数据降维**
当拿到的数据维度很高，且比较稀疏或有噪音时（真实的信息量远小于数据的维度），可以对数据进行降维。

数据降维旨在**减少数据的特征数量**，又尽可能保留重要信息。这对于高维数据非常有用，能够降低数据的复杂性，减少模型计算时间，还可以防止模型的过拟合（学到不该学的噪音等）。

常见的降维方法有两种（特殊情况下可相互转化）：


### PCA（主成分分析）

通过**线性变换**将数据从**高维空间**映射到**低维空间**，同时尽可能保留原始数据的方差。目标是找到数据中主要的方向，使得数据在这些方向上方差最大（**方差越大信息越多**（分布更加的散））。

* PCA 步骤（不用理解，保留印象）：  

  1. **数据去中心化**：对于一个特征矩阵 $X \in \mathbb{R}^{n \times d}$，其中$n$是样本数，$d$是特征数。

     去中心化后的数据为：$X_{\text{centered}} = X - \mu$，其中，$\mu$是**特征的均值向量**。

  2. **协方差矩阵**：计算去中心化后的协方差矩阵$\Sigma$：$\Sigma = \frac{1}{n-1} X_{\text{centered}}^T X_{\text{centered}}$，$\Sigma \in \mathbb{R}^{d \times d}$ 反映了特征之间的**相关性**。

  3. **特征值分解**：对协方差矩阵$\Sigma$进行**特征值分解**：$\Sigma v_i = \lambda_i v_i$，其中，$\lambda_i$ 是第 $i$个特征值，$v_i$是对应的特征向量。

  4. **降维变换**：选择前$k$个最大的特征值，使用对应的特征向量 $v_1, v_2, \dots, v_k$构成主成分矩阵 $V_k$。

  将数据投影到新的低维空间：$X_{\text{pca}} = X_{\text{centered}} V_k$，其中，$X_{\text{pca}}$​是降维后的数据矩阵。

> 使用场景
> * 数据中的主成分是**线性组合**的，不适合处理**非线性数据**
> * 数据中的**方差具有**足够的**意义**
> * 当特征数**n**远小于样本数**m**时（计算比SVD更快）。

In [10]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# 假设X是输入数据
X = np.array([[2.5, 2.4, 2.3], [0.5, 0.7, 0], [2.2, 2.9, 2.1], [1.9, 2.2, 3]])

# 标准化数据
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("标准化后的数据：\n", X_scaled)

# PCA降维
pca = PCA(n_components=2)  # 保留2个主成分
X_pca = pca.fit_transform(X_scaled)

print("降维后的数据：\n", X_pca)

标准化后的数据：
 [[ 0.94637923  0.42679753  0.40209035]
 [-1.6643221  -1.64621905 -1.65303809]
 [ 0.55477403  1.03650829  0.22338353]
 [ 0.16316883  0.18291323  1.02756422]]
降维后的数据：
 [[ 1.03036351 -0.16707256]
 [-2.8653447  -0.04810784]
 [ 1.05431008 -0.48854595]
 [ 0.78067112  0.70372635]]


### SVD（奇异值分解）

利用矩阵分解技术，将一个矩阵分解为三个矩阵的乘积，用于理解和处理数据的潜在结构。
* SVD  步骤（不用理解，保留印象）：

  1. **矩阵分解**：对于一个矩阵 $A \in \mathbb{R}^{m \times n}$，它可以被分解为三个矩阵的乘积：$A = U \Sigma V^T$，其中：
  - $U \in \mathbb{R}^{m \times m}$ 是左奇异向量矩阵。
    
  - $\Sigma \in \mathbb{R}^{m \times n}$ 是对角矩阵，其对角线上的值为奇异值。
    
  - $V^T \in \mathbb{R}^{n \times n}$ 是右奇异向量矩阵。
  
  
    2. **奇异值**：$\Sigma$中的奇异值 $\sigma_i$ 是矩阵 $A$ 的重要性度量，按从大到小排列。每个奇异值与对应的奇异向量共同决定了数据的主要方向。
    3. **低秩近似**：通过选择前 $k$ 个最大的奇异值，可以得到矩阵的低秩近似：$A_k = U_k \Sigma_k V_k^T$，其中$U_k$ 和  $V_k$分别是前 $k$ 个奇异向量，$\Sigma_k$ 是对应的奇异值。
  

> 使用场景  
> * 应用更广泛，可以处理非线性数据。  
> * 当特征数**n**接近样本数**m**时（计算比PCA更快）。  


In [11]:
from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import StandardScaler

# SVD降维
svd = TruncatedSVD(n_components=2)  # 保留2个奇异值
X_svd = svd.fit_transform(X_scaled)

print("SVD降维后的数据:\n", X_svd)

SVD降维后的数据:
 [[ 1.03036351 -0.16707256]
 [-2.8653447  -0.04810784]
 [ 1.05431008 -0.48854595]
 [ 0.78067112  0.70372635]]


### **数据集划分**

为了确保数据对训练有效，我们通常将数据划分为**训练集**和**测试集**，分别用于训练模型、测试模型。这主要是为了避免“**过拟合**”问题。

> **过拟合**是指模型在训练数据上表现得过分卖力，但在新的、未见过的数据上表不佳。通常是因为模型记住了训练数据中的噪声，而不是学到了数据中的真正规律。

通常，训练集和测试集的划分比例为`7:3`或者`8:2`。

In [16]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# 加载数据集
data = load_iris() # 鸢尾花数据集，其中data和target分别是特征和标签
X = data.data[::15]
y = data.target[::15]

print('划分前(X):\n', X)
print('划分前(y):\n', y)

划分前(X):
 [[5.1 3.5 1.4 0.2]
 [5.7 4.4 1.5 0.4]
 [4.8 3.1 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [5.  2.  3.5 1. ]
 [6.6 3.  4.4 1.4]
 [5.5 2.6 4.4 1.2]
 [7.6 3.  6.6 2.1]
 [6.9 3.2 5.7 2.3]
 [7.7 3.  6.1 2.3]]
划分前(y):
 [0 0 0 0 1 1 1 2 2 2]


In [17]:
# 将数据集划分为训练集和测试集，这里训练集:测试集为7:3
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
'''
test_size: 测试集比例(默认None),可以是0.0-1.0之间的浮点数或整数
train_size: 训练集比例(默认None),与test_size互补,优先使用test_size
random_state: 随机种子(默认None),保证分割结果可复现
shuffle: 是否打乱数据(默认True),分割前随机重排数据
stratify: 分层抽样依据(默认None),保持原始数据类别比例
'''
print('划分后(X_train):\n', X_train)
print('划分后(y_train):\n', y_train)
print('\n')
print('划分后(X_test):\n', X_test)
print('划分后(y_test):\n', y_test)

划分后(X_train):
 [[6.9 3.2 5.7 2.3]
 [7.6 3.  6.6 2.1]
 [5.7 4.4 1.5 0.4]
 [4.8 3.  1.4 0.3]
 [5.  2.  3.5 1. ]
 [4.8 3.1 1.6 0.2]
 [7.7 3.  6.1 2.3]]
划分后(y_train):
 [2 2 0 0 1 0 2]


划分后(X_test):
 [[5.1 3.5 1.4 0.2]
 [6.6 3.  4.4 1.4]
 [5.5 2.6 4.4 1.2]]
划分后(y_test):
 [0 1 1]
